global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mcp-server"
    static_configs:
      - targets: ["mcp-server:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "streamlit-dashboard"
    static_configs:
      - targets: ["streamlit-dashboard:8501"]
    scrape_interval: 30s
